---
title: "showdown"
author: "Jarrod Pelkofer"
date: "July 24, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Load data and libraries
```{r}
library(tidyverse)
library(janitor)
library(ggthemes)
theme_set(theme_fivethirtyeight())


hole_data <- read_csv('hole_level_data.csv')
rd2 <- read.csv("rd2.csv")
rd2 %>% mutate_if(is.factor, as.character) -> rd2

rd2$Player[rd2$Player=="Rafa Cabrera Bello"] <- "Rafael Cabrera Bello"
rd2$Player[rd2$Player=="Alex Noren"] <- "Alexander Noren"
rd2$Player[rd2$Player=="Matthew Wolff"] <- "Matthew Wolf"
```

###Showdown Scoring
```{r}

#Showdown Scoring
plyr_rd_scoring <- hole_data %>%
  clean_names() %>%
  mutate(double_eagle = if_else(double_eagle == 1, 16, 0),
         eagle = if_else(eagle == 1, 11, 0),
         birdie = if_else(birdie == 1, 5.75, 0),
         par_2 = if_else(par_2 == 1, 1.75, 0),
         bogey = if_else(bogey == 1, -1.8, 0),
         double_bogey = if_else(double_bogey == 1, -3.9, 0),
         triple_bogey = if_else(triple_bogey == 1, -3.9, 0),
         three_birdie_streak = if_else(three_birdie_streak == 1, 5, 0),
         bogey_free_round = if_else(bogey_free_round == 1, 5, 0),
         hole_in_one = if_else(hole_in_one == 1, 5, 0)) %>%
  mutate(tot_pts_hole = double_eagle + eagle + birdie + par_2 + bogey + double_bogey + triple_bogey +
                       three_birdie_streak + bogey_free_round + hole_in_one) %>%
  group_by(tournament_id, tournament_name, round, player_id, player) %>%
  summarize(dk_pts = sum(tot_pts_hole)) %>%
  arrange(-dk_pts)

tourn_rd_score <- plyr_rd_scoring %>%
  group_by(tournament_id, round) %>%
  summarize(avg_dk_score = mean(dk_pts),
            med_dk_score = median(dk_pts))

showdown <- plyr_rd_scoring %>%
  left_join(select(tourn_rd_score, everything()), by = c("tournament_id", "round")) %>%
  mutate(dk_pts_over_avg = dk_pts/avg_dk_score,
         dk_pts_over_med = dk_pts/med_dk_score) %>%
  ungroup() %>%
  add_count(player)


```


###DK Analysis vs Field Avg
```{r}
showdown %>%
  left_join(select(rd1, player, Salary)) %>%
  filter(Salary %in% c(9100:11000), !is.na(Salary)) %>%
  mutate(plyr_sample = paste0(player, " (", as.character(n), ")", " (", as.character(Salary), ")" )) %>%
  ggplot(aes(x=fct_reorder(plyr_sample, dk_pts_over_avg, fun=mean), y = dk_pts_over_avg)) +
  geom_boxplot(fill = '#F57921', color = '#472F91') + 
  labs(title = "DK Points vs. Field Average 1 Round",
       subtitle = "2018-2019 PGA Season (sample size)",
       caption = "Data Source: advancedsportsanalytics.com") +
  theme(panel.background = element_rect(fill = 'white'),
             plot.background = element_rect(fill = 'white'),
             plot.title = element_text(color = '#472F91'),
             plot.subtitle = element_text(color = '#472F91', size=12),
             plot.caption = element_text(color = "#472F91"),
             axis.text = element_text(color = '#472F91', size = 12)) +
  coord_flip()
```

###DK vs. Field Median
```{r}
showdown %>%
  left_join(select(rd1, player, Salary)) %>%
  filter(Salary %in% c(9100:11000), !is.na(Salary)) %>%
  mutate(plyr_sample = paste0(player, " (", as.character(n), ")", " (", as.character(Salary), ")" )) %>%
  ggplot(aes(x=fct_reorder(plyr_sample, dk_pts_over_med, fun=median), y = dk_pts_over_med)) +
  geom_boxplot(fill = '#F57921', color = '#472F91') + 
  labs(title = "DK Points vs. Field Median 1 Round",
       subtitle = "2018-2019 PGA Season (sample size)",
       caption = "Data Source: advancedsportsanalytics.com") +
  theme(panel.background = element_rect(fill = 'white'),
             plot.background = element_rect(fill = 'white'),
             plot.title = element_text(color = '#472F91'),
             plot.subtitle = element_text(color = '#472F91', size=12),
             plot.caption = element_text(color = "#472F91"),
             axis.text = element_text(color = '#472F91', size = 12)) +
  coord_flip() 
```


#Density Plots
```{r}
showdown %>%
  filter(player %in% c("Jim Furyk")) %>%
  ggplot(aes(dk_pts_over_avg)) +
  geom_density(aes(fill = player), alpha = .3)


```


###Simulations
```{r}

showdown %>%
  filter(n>50) %>%
  distinct(player) %>%
  pull(player)

player_sim_data <- showdown %>%
  filter(n>35) %>%
  group_by(player) %>%
  summarize(avg = mean(dk_pts_over_avg), st_dev = sd(dk_pts_over_avg)) %>%
  ungroup() %>%
  mutate(sims = 20000)

set.seed(33)
player_sims <- player_sim_data %>%
  rowwise %>% 
  mutate(rd_avg = round(mean(rnorm(n = sims, mean = avg, sd = st_dev)), 2),
         perc_10 = round(quantile(rnorm(n = sims, mean = avg, sd = st_dev), prob= .10), 2),
         perc_25 = round(quantile(rnorm(n = sims, mean = avg, sd = st_dev), prob= .25), 2),
         perc_75 = round(quantile(rnorm(n = sims, mean = avg, sd = st_dev), prob= .75), 2),
         perc_90 = round(quantile(rnorm(n = sims, mean = avg, sd = st_dev), prob= .90), 2)) %>%
  arrange(-perc_75)

rd2_sims <- rd2 %>%
  clean_names() %>%
  select(player, salary) %>%
  left_join(select(player_sims, everything()), by="player")

```



###Analyzing Sims
```{r}
rd2_sims %>%
  select(-avg, -st_dev) %>%
  filter(salary < 7800) %>%
  arrange(-perc_75) %>%
  head(20)

```

###Sims Charts
```{r}
rd2_sims %>%
  filter(salary %in% c(6000:7400)) %>%
  head(15) %>%
  mutate(name = paste0(player, " (", salary, ")")) %>%
  ggplot(aes(fct_reorder(name, perc_90), rd_avg)) +
  geom_point() +
  geom_errorbar(aes(ymin = perc_10, ymax = perc_90)) + 
  coord_flip()
```

